apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: demo-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBp7l11iEWSlauJuK/38UevSPVkLbj8AWK1z/fmd0BoEPZpagZ9norBKSYqpbht2bxVJvvBRLXi4R+FTNYlMLLszyutvRHGPB4iTEdYihaacboN49CLNoD1yN1JP7+Z8KPP2jiS7V3ddbCnWdpVs6jP39gRIqzbAP5GGknOurigbwIhFsZFT44lCyYUABB230KcA/MpbPHH35kDMg/Wea6moUjU5UNl+SL7ia8jxNZoV4LmpLYfMVKsUidEdqWYHj6fscMFT8qpH1nP8RtHbGEZhJgpbNtuSuABTEJbq42pp1vuhh7INzOkhBYsfzteuZaFHv0xFBKvLpuO6eJQf+kLbDH0Zk836rDd9Y6iORmA/mBIb8xpfdIsmbzQOvBxo4MBDclsATO9wSkBtzQ3AqtgfifcSZw6hhbAmCxIMInEQ06Lmnx2YGPArNl1LZmT/7TAWNzjtvBrj5w2GGVRis8q0qouszeSTFOoPf84CFHGFRgK2kQnwf80XghzxO8sDlJZkw2YDfRypT10eZIGbMdJCjte87dSiDGBEx73kvKuwNIogT0yB5wdAleuD6HxU6QeULmwrA3NjduWfU+ioqdO8FIFT0STRLOINfsJP0MmhMP3zrF9C8MxkC7Im2Kzz0aAFHvJUSfLiBDJqMdI8SytcxLjTBguelXXNncrBkOokdjQvecd1rcHc2e5igkINul+Ijqq0uYRtz6FLC0e7sQW+hqTJVGU35PNjt662dtUWqQ4JT//dCg/a8681DanjbMXOK9bip29GUk31ckserieb4FGNefbFT1Rt6FDQBW3zflJml0nmSaldsf0YVCGBjAcxgUzsWCPve7dzbT+TYWbLkJCJS/BL3yuRCIO0pL53B8ci/uPqeypulloAIAh707jQnUcqV/5xiubwHLMkrL+ZkWS+kwHI3pFhVAsqdGgO9CPjjMbk1fcGRo6
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: demo-cicd
    type: kubernetes.io/dockerconfigjson
status: {}
