apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-webhook-secret-taxi-svc
  namespace: demo-cicd
spec:
  encryptedData:
    webhook-secret-key: AgAxI62pbGbi7mgVmcN8FinM1NUY54x8DvCL155TIgFu01i2wWij7kT0CZufFUrhA9Sv2hhseybWQlNofgz7U+4qv0JMM3XarZw3jI43dsB49OPJhcLtGGrBxDieulUG/rDQMOrcNJc4suZRGkE723SajcdWzE/lvmvkPcJ1pC/TGhasOQOzv6o7wsVLtQUDivtMGbVrYLRTPt5XhOxRHrs1Yz45MYJpshzuPt53Aa3IrHxh8NLLYHs2x5wFFwdIqaZPYM1KlsEudcw/8MLJ8mH/KfSm0L+NGIwqmTfVibLPwivekTGQ4KJx64/4vq0t+rrLpNCdNE+zTvj74YCxLyGKJVqqxe1qMOmqyXGOwXuNpz+6PmE1cWHKwnCN9nbYW6TjLrGokcarWf5AuIcdn6U7cqTyhrdrn5qdjXaVcVdPHlV6fwrda8xD7X+ZW/rUfkD6Yn3KSvyhpqp6fdgGTpqtcq5p3pCwaBSoMlU9eX2C1m0dCR494lV2C+4dQe6K7DJVmCrvuwAHcx9cshj8Rt8a+fYJXaEx7JGCdmbE2Y/5xg4SUmmBtBafj22EddKx4mDs+qlzScLm6IC/mIsqExPxIjr7xLh9y/CDQNwg1ECIHRuVtn4d5vyXec9Nlc0iCeSU/SpEd3AZxv/AjhxXHEs5dQ/xfIpNDygrFAhO0RnhtRvKwcNdJedgdFBXsdnDu9V+OfQLhNA=
  template:
    metadata:
      creationTimestamp: null
      name: github-webhook-secret-taxi-svc
      namespace: demo-cicd
    type: Opaque
status: {}
