apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAgHFDAWoYh2fEry0nQCiRIjpM5ZD0nDFlsuwSwpDEVuwRQMPSPSFOUIKIDdYr3/OAWJeNuybq9oD2Q+XqzyFglKAS9EJfhIvt775jupxlQ9AAkBeVHXtKm+Dw5w8iqPTX0bx61EJHqYn1+yl3TD4jRXUuXcjNm98LdKkUXJqXq1dJtkoXWPokA59uDRN22t9BVjo8pFLAvT9OvKTZUBuvhnrKQrbP3pZcRVX2y4epddUcVc2G6+wuA4r2Mqt5SAvtwNQCsSJ/8GOoeTWhCcT5Gj140sxahMsf3aZeZ8yA/g8/WUzq7R1E75MGEeBvxsaoEbDZzqniJKbXFRF9iV0IEtElfcYXpAVjP0AjET4WIdVFppZpXck6Ty+DmXQAGmTgFqgCZcWfO8UU6c8VtBkJfS/kw+7uS7pFjWGfV75E3hglx5SqXUPBc9aQ6ZT62OcEB/HuFXiKXzg1IpES9Z2CoOgHCeAtgXxUkzTMYKcW0lzFb+fD5kwu2e26Bhg056dTwF6oai5LwopSY5J3g0Gvu+cA0hkdomL1czfUI0yKohnOUGjsZN3SCgvVi48CxBMizQvLc/0suYEQm9qsyfliTzs5Z++kQ7pTU6cDnLtHiQ+IQh+KRF7+uNwOCsAkyjVKElW5wJrFCQpSmesFAMgvVyJkxDHrxBmUmXIJeuevfeZ9ezD0OmXOAT1T1qTGFp7YwLzclHr1SP/uZ4qOfGISwRp6ccHkpglrG9G8RQPSnqDZ34MgXqEujf2xClLKjdjLdiEeY++ejA3zubtS6FcqfrTlcVke3lEP+QCDA37fHs+unUtZMbmUAfPBjQqCKbG4gfNCmk/1FAhOaGVEpyeQ+EM4S38QToJl3mkaJFw2/NR+6UVd4wttMODxoN0U2LCbX5gUeE7NBL+XmFTsJXBSgX4/QaP/P11UAPNAo/DhOclderC/laQUblQDi
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
