apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-webhook-secret-bus1
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAvSK1HS1tyuB9PeZeoeQDYYSY6IrbPt5rj8fLOhQyAHmXFQbXH6m1ER0S78XJnDqlxvufJqD+bYnNKz7gx4Z9NS50WEEazufOZZcoFCGRoZB685QWn7debUtbeYIPq0HXu8O664rEYQqOqkr8wlyyPRqNkiQT6jdAMhwX6YFMPPHEikqqFOFtFTw4gcDN9nPlzgT8Ng0sxGK/QYkvDwB+/PSpNCRiq52L3HQCMtx45KfMgwhmfLiVUWbheZD1meINs+K/rEWkr+UF59fH7dbYJGJs6pCOrb5rphbbQ6cGn1Hq/vvS07LHQ3GVIl8fqCtOBWHUrWde9ngHRKEdnJZNuHQSs5/83ymylLvOM0BPdeIRAEd90dYsNc13/DzXw10Sqp+Y5TzOb4GpS1Gy6juNrH6QntFkvOFmLsPyD1BGk5Ma0wGyYBmTYzGJJ67m6d7TORCSDD3I6jYJgx0I0GcEPoN3bYR5Sp4VTQVH7KP+66Eb3tnWNftbueeCCQjwBwSngrdDEBMAeqixMb2RA3TndHYcojmby94zaSAJ1FCNaINW+xR47JsvzgWUFHviudxXCknWGU5h7w1hoYxaWZpf2P4DoeH0q0vchIaKlwGVk8x9SNaM7H6z394UybR7ygjZZvES0Mdyxgv5YGlF74v+W7CZlBAHz2CYNKZAdQB5IuypX0pfCwkH1//OlkPVGLLLUQ9FZ5Q==
  template:
    metadata:
      creationTimestamp: null
      name: github-webhook-secret-bus1
      namespace: cicd
    type: Opaque
status: {}
