apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-webhook-secret-taxi-svc
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCLRlTqkuscNUrWUmCOpD+fgiPX09n616A8xtUKDI1fV1yXdwmIcDQ/O86GhiCMz1VmLOT/jxVNAkpvRT3xcrgMxWAJZc7A09TJyo0pm6V8KsmoY1XHNf9bMiQ1mimS0bmrYlpkjQj0qVeVffKThEzOvdtHBkeGezolSPfpvpGm7I3X4gV8nyFaKYsb1iT+/8L6wFgHikcbgWd33AiVOCSZafcJMfAE+T0OF9tDWSn+j1ZUMuCqkrgTn6Hcqtd1RZ45q+qwDkfjpwlXk9sSS+2wF3m6zJ6t3bhNP1LdEA6eJTKu47AGbJbeF2lDG5FG4MZQgV2zPbMuIKBwTvcElHhFKv4ad2qrIHFfdI8TnNufgZj8c3CZiNVAV0c4i5wBPU4C8h+FZiahBx5VvxaLKDdSq/qbALxNeIUX3kXxUqjPTgUhz7Vii+/QPHg6hWmS6021IiTC0FVNipk99+4TccgeOPZN8ky7QwwEu3w7R/h5lpflHrmeKBwJRi9xH2fbmCJB6plN942+kMHuxNb3O7+qFeI2SvMRfIergbwkV7pqQXR2k/nGyO55drWkQEkS8dRBY4Mwrwvf/vYEnPnPz4yphnO70v2/bGqmw0N7Kw7G1/Uv+0FppVFTm6tMlGGHBTuIKPsN6NjqrJUPDcB7ekRo0ADYsXFcDo3MhF7NK4EZTgoizzDobBp2oMK44uiwxHuGoQSlNP8=
  template:
    metadata:
      creationTimestamp: null
      name: github-webhook-secret-taxi-svc
      namespace: cicd
    type: Opaque
status: {}
