apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgChc6jBWQQnOzTTCqPPCs3UBjYUkhoNMY8uoCBYH2OIgRxS9vwl6eNuUMXgs58C4orMqCe4osz56G7n6Npp0XNhMFb2hwTHJQpfWWCW4Zdi7h9oLkNSoSS6s2jD8N2xV15QNequHJUzijPthXI8fzbBpGI6sf1rhHfo242Ri3sMDlcKiAjw8dfFHwuX3qJvFdRpOE1ZkFQ05oyR9OOUwr2myG52jpJJv79r/YHyqQHWgcKFcC+9splI1ytS3iz5zwuf/EjB4qacRU9K2cqebIl2OGthtQFWW3IUXurW9amz1z/pxP+qdLRwKBZPgsetQO/jO0g+I04YtFGm5QmJTBB7NlmJL5WJV3X17TESrhgz4A4arORj8Y8wbu4e0wqPbBMu54cOk7O90Fn7QAgjp202FT8WW0vGPahSK/koFVMbFN7Maevq4HHMLOqjyFPjf5FofZkfcqWsMwdle45JXMtUIFwOiWTPyqDFBwEQnTJcuN45GrtLCUW/J24Eu7IewfOsDPOyZzsIHtwr6POFgR+azVyKNNgtnn4DgrZiNb4cmOTmfhGN5Ou5QJ1CdhbLTVr8p6119a1UXkMxCspPoVLVM5xl0/Y/EY/9mFNlD1KXyZGyf4SR0VWpkv2qLnpcl0byEcmOgd9W/MnO/TiFgF6nvfiWOprwWyC3yXkIdp0L+Y6mAxJ7CNMjqgC61EyiT7fXQ+1AWiE=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
