apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: t4-cicd
spec:
  encryptedData:
    webhook-secret-key: AgCTgeJO2sLH45XWiUNtZlXTSRAkNtyZHaY8IcC1w5d/5b7UNiMx5HSs/fmtNF2b5nQDCE3zeNlB35Uo7FZvLVZxj4tAF13pAIhbfsy5DtZalbXZYIyKh/oYK9SILZeqZlFfKv7EO4TO3NHnnnnEMQyzrg6xJbGdOhDmUnFDc6YgoUhfmtEjB3ty9is6TGJuSyFTfWvMkR+8ws5URykOVQlxJZK7OAFxK9fkFFuwP0CEiDt93XhCaO4aiZ0NY4gitk29479Pw8OlzyMv9DRIxN4+hyUcdmtC2kiRMtBTFmJ1GwjprGQk8GCRyEj6LT6NDZapV1Fx2qS1GuiC3NoU9H9CoCjjhY93RT+PkU73JHDH+m49+YXXY3+VCSgOGhGELf09Sk8T/8p/uI6Tw1wJZu6eiT/bG8JQVrGM/8OWDZlkx6fqWtzv3SAo/pyPIGkmn7JSx/Z8cpLlqwPCyCoP7EBJvomClJwPNz39mo1fn1/PlAjmnDFz7OTSE+IlkByuduEZ5+VFDxkhQ2aAPHuOeiqNY+7tVUgNmBWKrCdOuaQo58hTZJM+XR00YJCqpiwRrT5NfL2AtPaSqrONZTd0gUTN3RG+nkaX9fj7eB3VIh1zI9S/X8VIOQZ674nhQXBiMjNoCBqVGadhMgf2g2fz6oQhJDDdenjNown7e07Ndwb2dvchwHT3IuxM+AhIM4QqcovCpOuZQrw=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: t4-cicd
    type: Opaque
status: {}
