apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: demo1-stage-bs
  namespace: argocd
spec:
  destination:
    namespace: demo1-stage
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/demo1-stage/apps/bs/base
    repoURL: https://github.com/ishitasequeira/gitops2.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
