apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: demo1-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCfKVkd0cJpbA13roQQCN9Rw9Eli5X8P03dxW7r+aAeuZmwmtOvAR51nuMssw3Y0/F/O0GfAdC0f+mjw8hAEvZcmHLqKggnkJlKN6wmJaCq1o9JwhyzA7Zg1cIiygFiZFqltWT7GIRHUIfnQvhGr9VrvFLerUG+kiLW761NQcpf6h/gCZgCPwZV0HJr6ZJaO0O+5Kos5WXXJXEllsEhJRfAyXP+AEMQkKfq29THd15Wh5RtXSkO/AXB5D0Kn0HzsWrXdAxJV8QPLnO6Niw9yTXginI1eKkGm4HY3FxtX35CylefTjWhxkv6fQcNjf0hu6tww6HxisqJ40d5/pthDaQZZacavQCrNjTtskArLooGaZMrRVDGb2hQDda8FTm7IPyWt4v1i8Rdb+qlMdbtOJu3+GctZlDjuMmcSpn6DDoI3gOMyPXuIywbR92JkpP4Fj3fXpy5hVtWv/wIslHqgDRHsuPEdEMb78K0BY0KLLdyL4W9xF+YDeIeU9jMWDmXbHi/3dFsnQid0+/mN2Qx1DNU7XJelkNZ6GDAPU4HUYb5gMnOmGle3xF3ahJiokX+BvXMrx9zXdcBGP8VUbA48Rl3aK5TtXH6vN9ina6MqO6ktJWzv4QSImqrL2b3nP7Qi/+PL4lrtnqkZklpZ2k9z6kMbWBirpeKv2HeP29I0KvzgvJO0GM+A3Lgl1J0wizJkz52azuSXrFM7AbLa91//tP845kZcK+IhKgFIjrSRKdkDWZcBRnD2u84na89J+AYtVBcRKV/GCSWmZzBaXEios4w3UKA6iIrGXTHY5A5wwN/F4xFZ7ei2Pyo0snXfbG6+NeU/VKeiOXg/tflPiWIqi+SCdlgBRySU9DkqpB1u8RSJHGOhodSXHz086q3o0CkY7oJDUcNMfgzdUEkRQWhXg2/gBD0/aXUKwbRC7Dc9E2RaYdjNcwr2QsSkhzM
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: demo1-cicd
    type: kubernetes.io/dockerconfigjson
status: {}
