apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: demo1-cicd
spec:
  encryptedData:
    webhook-secret-key: AgB9NV5sPmXHMFmBq2P43wJJ7gZ96gZVw4IT598IhOZLbdSotLmsKQ+yQJfu7beL+mXcE0CIOS9jnY1UkBnFKHvykYga63Fy9j05WAsl9Cab1P9K34X43JYUQxnW5k3Ec4+3F5r1BTRvW3CxmSPkZsgDVLkC4JFD7qmBwpflUBTbeuOesDawMoBLenGM9QaAycK/AjBRhbiz2iavOmrrI6FATPEbI4ZtZq2Y5uW1PH8Kw97cNN78+foJJFmYDgp/Qrx00IW0ruzO2YIsZ5Uca0SnKm3QuwmHZSJeBNzZ9hurNgcVYEc4z/G9W3cAHpoWlv/XqW4q5fnnu8kn67YVkR2uJFn/4OYpbGqxq83OZeZwQfCw9w7V1vEqjws/j9Rzc/z88gMWvhl77zFrW0LzBEntmoF0+NUYsFdxqb2gBCJU8VyCu8s03Jnon7krf/CAfW/xtU4x3/MM6YJ6e2khNTKyhbloSnWS9/SyQ72+wQ8IwQ7fw7HjJKm3WCOMcLrSvrcovyFDEwqgAbGXf9es+qwx0WyxFEz7dZFgfDg/ygJDkgE6h+uO6fLC6kVqqyjPAHTKqdqZaE2hXfillA9ocYTW49tknGqQ8nXRvb26NhdFvIm1reehfbL+7up5Vap4368EfuXdLknpYbXVQDR+MMTI8pHSLn+Yu257q8Dj7N+0tu3MyxhSbTUc0mgfUVk5ZmkvAaQuTV4=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: demo1-cicd
    type: Opaque
status: {}
