apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-webhook-secret-taxi-svc
  namespace: t5-cicd
spec:
  encryptedData:
    webhook-secret-key: AgB3omw1goZPmIyVEMeQ9MaMB8uvJ1ydKFA7MxEAqtXqht67ljOXL/7hGY0GcO50icz1GC7FjbzrV1OSAxJMjfyhcFh32Y7gVj+Bfu02xAj4CXfjjiYPvRwprfkd50GVVVGTnQKmBShLlm0JeuAKUSdetJKbRR822Al/oJcqGzRnBTPsYjM1gbz6kCnph6vj9f/zLPc+sfREuSuvxBs3z5NIwIUYm9sVUQv4iuJ6YAI3w6YI07jLt6c00gQzVigXO3EzNBcUyTWmLPMUmLtAQCR67/ZjFyP+x7GqIj4tRUQAirK2FPgM/UARvm3Bi6YDcBC7aFzWnWxfcuZ+TWdnw3HCYEw1fTJ2BwZBRBxfH2fTNznar89RPRTWWmNMXEtHHPVZfYogbidoXGsvgYdhx3ffvun/FbEhGGdxhs9qBXXQCLmOahMAdCX6IpGfBymXiek1x2DJRS10Z3IHsmcNLCfx/uzM/oRM6cYH2KTRm9wilYD+46jf3/z9Gz6ssAZQBclzDpvTh1u48GKcX3z46+GVXbW4LIOpN6yMzbZz8NuWOVGv4L0kdFcNYocMTL1F1yK11xhMYEXrFKm8m13cRuv2Mgch9QK0qhcXGPAEIESp73e31GXJ5Gi+vL83x3wAEs5UYNAa1VrlfhfHhmHEg3YolQnGAy7hTx5FoBXUb84smk3IbSepYl7j1No4pGL0Pk5aBejfk24=
  template:
    metadata:
      creationTimestamp: null
      name: github-webhook-secret-taxi-svc
      namespace: t5-cicd
    type: Opaque
status: {}
